version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - storebridger-api-network

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ''
  #     MONGO_INITDB_ROOT_PASSWORD: ''
  #   volumes:
  #     - mongodb:/data/db
  #   networks:
  #     - storebridger-api-network

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ''
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ''
  #     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  #     NODE_ENV: ci
  #   networks:
  #     - storebridger-api-network

  app:
    container_name: storebridger-backend
    build:
     context: .
    command: yarn watch
    ports:
      - '4000:4000'
    links:
      - mongo
    volumes:
      - ./:/app
    env_file:
     - ./.env
    environment:
      NODE_ENV: container
    networks:
      - storebridger-api-network


volumes:
  mongodb:
    driver: local

networks:
  storebridger-api-network:
    driver: bridge
