name: Node.js CI

on: [push, pull_request]

env:
  MONGODB_URI: mongodb+srv://linkup:KZ7lmB8RLTA9DfPD@cluster0.qivfi.mongodb.net/store-bridger?retryWrites=true&w=majority

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install

    - name: Run Lint
      run: yarn lint
      
    - name: Run Tests
      run: yarn test
      env:
        MONGODB_URI: mongodb+srv://linkup:KZ7lmB8RLTA9DfPD@cluster0.qivfi.mongodb.net/store-bridger?retryWrites=true&w=majority

    - name: Build App
      run: yarn build
